name: GDScript Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Godot
        run: |
          GODOT_VERSION=4.2.1
          wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip -O godot.zip
          unzip godot.zip
          sudo mv Godot_v${GODOT_VERSION}-stable_linux.x86_64 /usr/local/bin/godot
          sudo chmod +x /usr/local/bin/godot
      - name: Run tests
        run: godot --headless --path . -s tests/test_runner.gd
